Демин Дмитрий Object Printer
kontur-courses/fluent-api pull request #109
Opened 2020-11-24 08:54 UTC by Dmitriy200123

https://github.com/orange-bird

2020-11-24 16:32 UTC, orange-bird requested changes

2020-11-24 16:32 UTC, orange-bird commented on ObjectPrinting/Core/MemberPrintingConfig.cs
> +            if (_memberName != null)
Если имя свойства/поля будет повторяться в разных типах, настройки будут применяться ко всем подобным полям, а нужно только для указанного типа.

2020-11-25 09:58 UTC, Dmitriy200123 commented on ObjectPrinting/Core/PrintingConfig.cs
> +            typeof(string), typeof(DateTime), typeof(TimeSpan), typeof(decimal), typeof(Guid)
Проверил, IsPrimitive возвращает true, когда float, поэтому оставил без изменений

2020-11-26 06:39 UTC, orange-bird approved these changes

2022-11-01 05:46 UTC, closed without merging