Поляков Илья
kontur-courses/fluent-api pull request #155
Opened 2022-11-28 18:44 UTC by IlyaPol92

@desolver, посмотри, пожалуйста

2022-11-30 12:34 UTC, desolver requested changes

2022-11-30 12:34 UTC, desolver commented on ObjectPrinting/ObjectPrinting.csproj
>      <PackageReference Include="NUnit" Version="3.12.0" />
Хорошей практикой считается разделение основного кода и тестов на 2 проекта, так тесты не нагружают основной проект собой и могут запускаться отдельно. Давай сделаем так же, соответственно и все зависимости тестов должны жить только в отдельном проекте

2022-11-30 12:34 UTC, desolver commented on ObjectPrinting/PrintingConfig.cs
> +                val;
Тернарники в несколько строк обычно по-другому записываются:
```
return MemberSerializationRule.ContainsKey(propertyInfo)
    ? MemberSerializationRule[propertyInfo].DynamicInvoke(val)
    : TypeSerializationRule.ContainsKey(propertyInfo.PropertyType)
        ? TypeSerializationRule[propertyInfo.PropertyType].DynamicInvoke(val)
        : val;
```

2022-11-30 12:34 UTC, desolver commented on ObjectPrinting/PrintingConfig.cs
> +            typeof(float),
- А как же всякие uint, ulong, short и тд))
- Сразу дам подсказку, чтобы ты не старался перечислить их все в этой коллекции, у типа `Type` есть свойство, которое может тебе помочь

2022-11-30 12:34 UTC, desolver commented on ObjectPrinting/PrintingConfig.cs
> +        }
Он точно нужен?

2022-11-30 12:34 UTC, desolver commented on ObjectPrinting/DictionaryExtensions.cs
> +    public static class DictionaryExtensions
Все экстеншны неплохо бы смотрелись сгруппированными в папочке Extensions

2022-11-30 12:34 UTC, desolver commented on ObjectPrinting/PrintingConfig.cs
> +        private PrintingConfig(PrintingConfig<TOwner> parent)
Приватные методы должны быть в самом низу, публичные выше всех, чтобы можно было явно понимать основные "способности" класса

2022-11-30 12:34 UTC, desolver commented on ObjectPrinting/PrintingConfig.cs
>          }
`nestingLevel` можно сделать со значением по умолчанию 0 и избавиться от этого метода

2022-11-30 12:34 UTC, desolver commented on ObjectPrinting/PropertyPrintingConfig/PropertyPrintingConfigExtensions.cs
> +                str.Substring(0, maxLength);
Тут тоже надо тернарник поформатировать

2022-11-30 12:34 UTC, desolver commented on ObjectPrinting/Tests/PrintingConfigTests.cs
> +        //TODO: удалить или доделать
И все же?)) Удалим или доделаем?)

2022-11-30 12:34 UTC, desolver commented on ObjectPrinting/Tests/PropertyPrintingConfigTests.cs
> +    class PropertyPrintingConfigTests
Нейминг тестов не совсем верный, предлагаю заиспользовать подход с `Should` в названии методов, тогда классы не придется переименовывать. Поправить придется все тесты(

2022-11-30 12:34 UTC, desolver commented on ObjectPrinting/Tests/PropertyPrintingConfigTests.cs
> +        public void PrintingUsingFunction_PropertyByName_Success()
- Если сделать в Person свойство Age полем Age (то есть просто убрать get;set;), то тест упадет
- И судя по коду поля в целом игнорируются при печати, хотя не должны

2022-11-30 12:42 UTC, desolver requested changes

2022-11-30 12:42 UTC, desolver commented on ObjectPrinting/PrintingConfig.cs
> +        private readonly Type[] finalTypes = {
Не вижу причин не делать это поле хэшсетом, поиск будет побыстрее

2022-12-01 17:36 UTC, IlyaPol92 commented on ObjectPrinting/PrintingConfig.cs
> +        private PrintingConfig(PrintingConfig<TOwner> parent)
Скорей всего я не выдерживаю везде это правило, но после прочтения Чистого кода, я так понял, что лучше все методы располагать максимально последовательно (в последовательности один метод вызывает другой), чтобы код можно было читать как статью в журнале. Или все же лучше еще учитывать доступность метода? И в какой последовательности, public, protected, internal, private?

2022-12-01 19:18 UTC, IlyaPol92 commented on ObjectPrinting/PrintingConfig.cs
> +                val;
Поправил

2022-12-01 19:18 UTC, IlyaPol92 commented on ObjectPrinting/PrintingConfig.cs
> +            typeof(float),
Изменил

2022-12-01 19:20 UTC, IlyaPol92 commented on ObjectPrinting/DictionaryExtensions.cs
> +    public static class DictionaryExtensions
Переделал.

Экстеншенов получилось много. А как можно было бы их еще разбить, чтобы легче было навигироваться?)

2022-12-01 19:21 UTC, IlyaPol92 commented on ObjectPrinting/PrintingConfig.cs
>          }
Поправил

2022-12-01 19:21 UTC, IlyaPol92 commented on ObjectPrinting/PropertyPrintingConfig/PropertyPrintingConfigExtensions.cs
> +                str.Substring(0, maxLength);
Переформатировал

2022-12-01 19:21 UTC, IlyaPol92 commented on ObjectPrinting/Tests/PrintingConfigTests.cs
> +        //TODO: удалить или доделать
Решил все же удалить))

2022-12-01 19:21 UTC, IlyaPol92 commented on ObjectPrinting/Tests/PropertyPrintingConfigTests.cs
> +        public void PrintingUsingFunction_PropertyByName_Success()
Поправил, протестировал в этой части

2022-12-01 19:24 UTC, IlyaPol92 commented on ObjectPrinting/PrintingConfig.cs
> +        private readonly Type[] finalTypes = {
А если после состоит из 10 элементов, то и в этом случае лучше хэшсет брать? Вроде прироста особо получиться недолжно. Или это больше на перспективу расширения, чтобы потом не забыть поправить?

2022-12-01 19:25 UTC, IlyaPol92 commented on ObjectPrinting/Tests/PropertyPrintingConfigTests.cs
> +    class PropertyPrintingConfigTests
Поправил

2022-12-02 12:43 UTC, desolver commented on ObjectPrinting/PrintingConfig.cs
> +        private PrintingConfig(PrintingConfig<TOwner> parent)
Да, располагать их нужно в порядке чтения, НО, модификаторы доступа тут приоритетнее. А располагается так: public -> internal -> protected -> private

2022-12-02 12:47 UTC, desolver commented on ObjectPrinting/DictionaryExtensions.cs
> +    public static class DictionaryExtensions
Тут смотря какой подход используешь при разбиении файлов по папкам. Сейчас ты разделил их больше инфраструктурно, выделил некие "экстеншны" для всего проекта и положил всё туда. Когда проект большой, экстеншнов будет ещё больше) И тут нужно решать для себя, как ты будешь разбивать по папкам проект: или как ты сейчас - инфраструктурно (если знаком с паттерном MVC, то представь что у тебя как раз три папки Models, Views, Controllers); или же разбивать "по фичам", то есть у каждой крупной фичи в проекте есть своя папка, и в ней лежат все экстеншны, модели и код этой фичи, и итоговый проект получается в виде набора этих папок-фич. Холиварная тема, правильного решения тут нет, нужно смотреть по ситуации) Но в данном случае не вижу ничего плохого, т.к. сам проект не очень большой

2022-12-02 12:49 UTC, desolver commented on ObjectPrinting/PrintingConfig.cs
> +        private readonly Type[] finalTypes = {
Ну да, понимаю, что экономим на спичках в конкретно этом случае, но тут больше на понимание что если коллекция используется только для поиска по ней, есть более оптимизированные для этого типы, чем простой массив

2022-12-02 12:52 UTC, desolver commented on ObjectPrinting/Extensions/MemberInfoExtensions.cs
> +            }
Для таких конструкций есть синтаксис лаконичнее, на мой взгляд:
```
            return member.MemberType switch
            {
                MemberTypes.Event => ((EventInfo)member).EventHandlerType,
                MemberTypes.Field => ((FieldInfo)member).FieldType,
                MemberTypes.Method => ((MethodInfo)member).ReturnType,
                MemberTypes.Property => ((PropertyInfo)member).PropertyType,
                _ => throw new ArgumentException(
                    "Input MemberInfo must be if type EventInfo, FieldInfo, MethodInfo, or PropertyInfo")
            };
```

2022-12-02 12:53 UTC, desolver commented on ObjectPrinting/Extensions/MemberInfoExtensions.cs
> +                    : throw new TypeAccessException("");
Тут тоже есть синтаксис, который упрощает немного код:
```
return memberInfo is PropertyInfo info
                ? info.GetValue(obj)
                : memberInfo is FieldInfo fieldInfo
                    ? fieldInfo.GetValue(obj)
                    : throw new TypeAccessException("");
```

2022-12-03 05:01 UTC, closed without merging