Карасев Артемий
kontur-courses/fluent-api pull request #170
Opened 2022-11-30 16:32 UTC by Rizhiy825

Привет, @Leoltron!
Я закончил работу над задачей, проверь пожалуйста)

2022-12-01 20:47 UTC, Leoltron requested changes
Очень неубрано в решении :(

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/MemberConfig.cs
> +        public MemberInfo propertyInfo;
Часть из них можно сделать приватными

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/MemberConfig.cs
> +        public MemberInfo propertyInfo;
Так propertyInfo или MemberInfo?

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/MemberConfig.cs
> +            serializerSettings.customMembs.Add(propertyInfo, objFunc);
Заинлайнь, не придется писать `new Func<object, string>`

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/MemberConfigExtensions.cs
> +            propConfig.PrintAs(x => x.Substring(0, x.Length - maxLen));
`x[..^maxLen]`

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/IConfig.cs
> +}
Не вижу смысла в этом интерфейсе

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/PrintingConfig.cs
> +        private Dictionary<object, Func<string>> customProps;
Не используются

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/PrintingConfig.cs
> +            return new TypeConfig<TOwner, TPropType>(this, settings);
Что тут с форматированием происходит? Это минимальное требования - пройтись решарпером, и это включает форматирование кода.

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/PrintingConfig.cs
> +            var memb = ((MemberExpression)member.Body).Member;
Пожалуйста, без таких сокращений. Лучше переименуй параметр `member` в что-нибудь другое.

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/PrintingConfig.cs
>          private string PrintToString(object obj, int nestingLevel)
`nestingLevel` не используется

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/PrintingConfig.cs
> +        private string Serialize(object curType, object curValue, int level)
Зачем тут `curType`? Тип `curValue` ты всегда можешь получить через `curValue.GetType()`

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/PrintingConfig.cs
> +        private string Serialize(object curType, object curValue, int level)
Увидел, что ты комбинируешь тип объекта и его MemberInfo в этом параметре. Это очень плохо, т.к. не только тебе надо понимать, что это в определенном контексте: тип или FieldInfo/PropertyInfo, так это еще и читать очень трудно.

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/PrintingConfig.cs
> +            if (curType is MemberInfo && MemberInBlackList((MemberInfo)curType)) return null;
Здесь и далее: `curType is MemberInfo member`

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/PrintingConfig.cs
> +            }
В чем тут смысл переменной line? Она везде сеттится и тут же возвращается, просто используй `return`-ы

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/PrintingConfig.cs
> +                curValue = TrySetCulture(curValue);
Не только "финальные" типы реализуют `IFormattable`

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/PrintingConfig.cs
> +        private string GetFinalStr(object objType, object objValue, int level)
Какое-то абстрактное название

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/PrintingConfig.cs
> +            return builder.ToString();
StringBuilder эффективен только при большом количестве добавлений

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/Settings.cs
> +            membersToIgnor = new List<MemberInfo>();
Куда e потерялась?

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/Settings.cs
> +            customCultures = new Dictionary<Type, IFormatProvider>();
Не особо понимаю, почему ты не можешь проинициализировать их прямо в объявлении поля

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/Settings.cs
> +        public Dictionary<Type, IFormatProvider> customCultures;
readonly?

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/PrintingConfig.cs
> +            builder.Append("(coll) ");
Что такое `(coll)`? Очень странное сокращение

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/PrintingConfig.cs
> +            var valueType = objValue.GetType();
Не используется

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/Tests/ObjectPrinterAcceptanceTests.cs
> +        }
Зачем здесь `[SetUp]`? Инициализируй объект в объявлении поля и оставь его в покое, ты его не меняешь

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/Tests/ObjectPrinterAcceptanceTests.cs
> +                           "[2, 5,3, 10,154, 13,15, -1,65]";
Эти тексты можно сделать чуть более читабельными в коде с помощью "verbatim string"

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/Tests/ObjectPrinterAcceptanceTests.cs
> +        public void PrintingConfig_MassiveInput_ShouldReturnExpectedLine()
`ShouldReturnExpectedLine` не несет никакого смысла, если ты не можешь или не хочешь описывать ожидаемое значение, просто опусти его

2022-12-01 20:47 UTC, Leoltron commented on ObjectPrinting/Tests/ObjectPrinterAcceptanceTests.cs
>      public class ObjectPrinterAcceptanceTests
Нет тестов на обрезание строк и циклические ссылки

2022-12-02 11:36 UTC, Rizhiy825 commented on ObjectPrinting/Settings.cs
> +        public Dictionary<Type, IFormatProvider> customCultures;
Не получится, т.к. настройки меняются в процессе работы над объектом PrintingObject

2022-12-02 22:15 UTC, Leoltron commented on ObjectPrinting/PrintingConfig.cs
> +            builder.Append("(coll) ");
Еще опаснее, enum это вообще отдельная песня в C#

2022-12-02 22:19 UTC, Leoltron requested changes

2022-12-02 22:19 UTC, Leoltron commented on ObjectPrinting/PrintingConfig.cs
> +        private Type[] finalTypes = new[]
Не используется

2022-12-02 22:19 UTC, Leoltron commented on ObjectPrinting/Settings.cs
> +        }
Не используются

2022-12-02 22:19 UTC, Leoltron commented on ObjectPrinting/Settings.cs
> +        public List<MemberInfo> MembersToIgnor { get; set; } = new List<MemberInfo>();
Почему тут `Ignor`?

2022-12-02 22:23 UTC, Leoltron commented on ObjectPrinting/PrintingConfig.cs
> +        public SerializerSettings settings;
сделай приватным, пользователю заходить туда незачем

2022-12-02 22:26 UTC, Leoltron commented on ObjectPrinting/MemberConfig.cs
> +        public PrintingConfig<TOwner> ParentConfig { get; private set; }
Тебе не надо его делать публичным. И не только потому что ты делаешь FluentAPI

2022-12-02 22:32 UTC, Leoltron commented on ObjectPrinting/TypeConfigExtensions.cs
> +            return prop.ParentConfig;
Внеси как-нибудь внутрь TypeConfig и тебе не придется публиковать поле `settings`

2022-12-03 07:27 UTC, Rizhiy825 commented on ObjectPrinting/Settings.cs
> +        public List<MemberInfo> MembersToIgnor { get; set; } = new List<MemberInfo>();
Это members, которые мы не включаем в сериализацию (игнорируем)

2022-12-03 15:53 UTC, Leoltron commented on ObjectPrinting/Settings.cs
> +        public List<MemberInfo> MembersToIgnor { get; set; } = new List<MemberInfo>();
Я не о том, куда e на конце делась?

2022-12-03 15:53 UTC, Leoltron commented on ObjectPrinting/Settings.cs
> +        public List<MemberInfo> MembersToIgnor { get; set; } = new List<MemberInfo>();
Ignore, не Ignor

2022-12-03 16:04 UTC, Leoltron commented
Этот тест не пройдет

```cs
        [Test]
        public void PrintingConfig_SetCultureForDoubleInsidePerson()
        {
            var config = ObjectPrinter.For<Person>();

            config.SetCulture<double>(CultureInfo.InvariantCulture);

            text = config.PrintToString(person, 10);

            var expected = @"Person:
	Id: 00000000-0000-0000-0000-000000000000;
	Name: Bill;
	Height: 175.3;
	Age: 35;
";

            text.Should().Be(expected);
        }
```

2022-12-03 18:51 UTC, closed without merging