Соцук Виктор
kontur-courses/fluent-api pull request #177
Opened 2022-12-01 09:06 UTC by viksot

Hi, @Folleach!
Basic requirements were implemented. Please, check

2022-12-01 20:35 UTC, Folleach requested changes

2022-12-01 20:35 UTC, Folleach commented on ObjectPrinting/PrintingConfig.cs
> +        }
What if I configure printer like this?

```cs
printer
    .Printing(x => x.Name).Using(x => x.ToUpper())
    .Printing<string>().TrimmedToLength(4)
```

I think this means that I want to trim _all the string values_. But I can't do it. What do you think?

Also I can't determine _multiple_ transformations for _one_ property :(
Like this:

```cs
printer
    .Printing(x => x.Name).Using(x => x.ToUpper())
    .Printing(x => x.Name).TrimmedToLength(4)
```

I recieve `System.ArgumentException : An item with the same key has already been added. Key: System.String Name`

Of course I can do it in `Using` statement. But via fluent api it looks better way

2022-12-01 20:35 UTC, Folleach commented on ObjectPrinting/Tests/ObjectPrinterTests.cs
> +    public class ObjectPrinterTests
I postulate to everyone to separate the tests from the implementation at the project level, but apparently the tests were originally inside the library...
Well, okay

But diffrenet project for test looks better :)
For example: I do not want depend at NUnit, because library from nuget depend it

2022-12-02 11:06 UTC, viksot commented on ObjectPrinting/Tests/ObjectPrinterTests.cs
> +        }
\+

2022-12-02 11:14 UTC, viksot commented on ObjectPrinting/PrintingConfig.cs
> +        };
\+

2022-12-02 11:58 UTC, viksot commented on ObjectPrinting/PrintingConfig.cs
> +                    throw new InvalidOperationException($"Object {objectType} has cycled reference");
\+

2022-12-02 15:08 UTC, viksot commented on ObjectPrinting/PrintingConfig.cs
> +        }
\+

2022-12-02 15:08 UTC, viksot commented on ObjectPrinting/Tests/ObjectPrinterTests.cs
> +    public class ObjectPrinterTests
\+

2022-12-03 15:55 UTC, Folleach commented on ObjectPrinting/Tests/ObjectPrinterTests.cs
> +        }
resolved

2022-12-03 15:55 UTC, Folleach commented on ObjectPrinting/PrintingConfig.cs
> +        };
`IsValueType` looks better, but cover too many types  
![изображение](https://user-images.githubusercontent.com/32067915/205449110-a1e27dbb-c5ca-46ca-ad2f-349f0f996c41.png)

![изображение](https://user-images.githubusercontent.com/32067915/205449103-75277fe1-c6e4-42fa-97ef-7fb487044f33.png)

2022-12-03 15:55 UTC, Folleach commented on ObjectPrinting/PrintingConfig.cs
> +                    throw new InvalidOperationException($"Object {objectType} has cycled reference");
resolved

2022-12-03 15:55 UTC, Folleach commented on ObjectPrinting/PrintingConfig.cs
> +        }
resolved

2022-12-03 16:07 UTC, Folleach commented on ObjectPrinting/PrintingConfig.cs
> +                sb.Append(PrintToString(dictionaryItem.Value, identation.Length));
append support fluent api too :)

```cs
sb.Append("\n" + identation + "[ ")
    .Append(PrintToString(dictionaryItem.Key, identation.Length))
    .Append(" ] = ")
    .Append(PrintToString(dictionaryItem.Value, identation.Length));
```

It's not need changes, just for your information

2022-12-03 16:07 UTC, Folleach commented on ObjectPrinting/PrintingConfig.cs
> +                return PrintIListCollection(list, nestingLevel);
Looks good.  
I would consider using `IEnumerable`, but it could be dangerous: re-reading may not do anything

2022-12-03 16:11 UTC, Folleach commented on ObjectPrinting/PrintingConfig.cs
> +            sb.Append("\n" + identation + "[ ");
`sb.Append("\n").Append(identation).Append("[ ");`  
I think would better. But this can be checked, for example, using [benchmarkDotNet](https://benchmarkdotnet.org/)

2022-12-03 19:06 UTC, viksot commented on ObjectPrinting/PrintingConfig.cs
> +        };
\+

2022-12-03 19:07 UTC, viksot commented on ObjectPrinting/PrintingConfig.cs
> +                sb.Append(PrintToString(dictionaryItem.Value, identation.Length));
\+

2023-11-23 04:56 UTC, closed without merging