Fluent api realization rshikhov
kontur-courses/fluent-api pull request #180
Opened 2022-12-01 22:00 UTC by Hrenaki

Шихов Роман
Наставник: @Leoltron

2022-12-03 15:29 UTC, Leoltron requested changes
Хотелось бы увидеть решение, в котором поля и свойства, которые пользователь не должен применять при работе с твоим FluentAPI, не были видны даже из тестов.
![image](https://user-images.githubusercontent.com/17354912/205448592-efc8c4dc-206c-42e2-bacb-456d801a925b.png)

2022-12-03 15:29 UTC, Leoltron commented on ObjectPrinting/Common/PrintingConfig.cs
> +            return (expression as MemberExpression).Member;
Используй `expression is MemberExpression memberExpression` чтобы не кастить лишний раз

2022-12-03 15:29 UTC, Leoltron commented on ObjectPrinting/Tests/ObjectPrinterAcceptanceTests.cs
>      public class ObjectPrinterAcceptanceTests
Нет тестов на требования задачи

2022-12-03 15:31 UTC, Leoltron commented on ObjectPrinting/Common/ObjectSerializer.cs
> +            var identation = new string(tabSymbol, currentLevel + 1);
Может, ты имел в виду «indentation»?

2022-12-03 15:34 UTC, Leoltron commented on ObjectPrinting/Common/ObjectSerializer.cs
> +                    CultureInfo.CurrentCulture = configRoot.NumericTypeCulture[currentType];
У всех типов, котоыре можно сериализовать по культуре, есть общий интерфейс

2022-12-04 19:25 UTC, Leoltron commented on ObjectPrinting/Common/ObjectSerializer.cs
> +                    CultureInfo.CurrentCulture = configRoot.NumericTypeCulture[currentType];
Вообще, я имел в виду IFormattable, там даже есть метод ToString(IFormatProvider), так что тебе необязательно менять текущую культуру

2022-12-04 19:32 UTC, Leoltron commented on ObjectPrinting/Tests/ObjectPrinterTests.cs
> +        private readonly static string newline = Environment.NewLine;
`using static System.Environment;` даст тот же эффект

2022-12-04 19:57 UTC, Leoltron commented on ObjectPrinting/Common/ObjectSerializer.cs
> +                    CultureInfo.CurrentCulture = configRoot.NumericTypeCulture[currentType];
Плюс в задаче идет речь о всех типах, поддерживающих культуру, не только "финальных"

2022-12-04 20:03 UTC, Hrenaki commented on ObjectPrinting/Common/ObjectSerializer.cs
> +                    CultureInfo.CurrentCulture = configRoot.NumericTypeCulture[currentType];
В интерфейсе IFormattable всего один метод:
string ToString(string? format, IFormatProvider? formatProvider). Судя по анотации к нему он дает возможность сконвертировать объект в строку с указанием формата.

Метод, про который ты говорил:
string ToString(IFormatProvider? provider)
находится в интерфейсе IConvertible )

Про сериализацию не финальных типов с использованием культуры понял

2022-12-04 20:09 UTC, Leoltron commented on ObjectPrinting/Common/ObjectSerializer.cs
> +                    CultureInfo.CurrentCulture = configRoot.NumericTypeCulture[currentType];
ToString принимает null в качестве формата, тогда объект сформатируется по умолчанию.

2022-12-06 08:13 UTC, closed without merging