Наташа Барабанова
kontur-courses/fluent-api pull request #90
Opened 2020-11-21 14:24 UTC by NataashaBanan

realisate
-Excluding type
-Culture Info for number  type
@goodoldlameme

2020-11-24 16:29 UTC, goodoldlameme requested changes

2020-11-24 16:29 UTC, goodoldlameme commented on ObjectPrinting/PrintingConfig.cs
> +            foreach (var func in excludedFields)
все что касается настроек для определенных полей - можно хранить не селекторами, а именами полей, тогда не нужно будет перебирать все исключения, чтобы найти нужное

2020-11-24 16:29 UTC, goodoldlameme commented on ObjectPrinting/PropertyPrintingConfig.cs
> +        public PrintingConfig<TOwner> Using(CultureInfo culture)
возможность настроить культуры должны быть только для типов, для которых это имеет смысл, например как с обрезкой строк сделать методы дополнения для PropertyPrintingConfig<TOwner, int> и т.п.

2020-11-24 16:29 UTC, goodoldlameme commented on ObjectPrinting/PropertyPrintingConfig.cs
> +        public readonly Func<TOwner, TPropType> MemberSelector;
это тоже должно быть только в интерфейсе видно, как и родительский конфиг

2020-11-24 16:29 UTC, goodoldlameme commented on ObjectPrinting/PrintingConfig.cs
> +            foreach (var func in excludedFields)
плюс сейчас будет эксепшн выкидываться, если настраивали для подполя сериализацию, например `        class Foo
        {
            public string Name { get; set; }
        }

        class Bar
        {
            public Foo Foo { get; set; }
        }

            var foo = new Bar {Foo = new Foo {Name = "Hello"}};
            var printer = ObjectPrinter.For<Bar>().Printing(b => b.Foo.Name).TrimmedToLength(2);
`
для такого объекта упадет сериализация, так как селектор был для Foo, Delegate.DynamicInvoke(obj) вызовется, obj будет не TOwner и все упадет

2020-11-24 16:29 UTC, goodoldlameme commented on ObjectPrinting/PrintingConfig.cs
> +            foreach (var func in excludedFields)
в тестах, которые есть сейчас эта ошибка не отлавливается, так как там только простые поля или поля такого же типа, как сам объект

2020-11-24 16:37 UTC, goodoldlameme commented on ObjectPrinting/PrintingConfig.cs
> +            foreach (var func in excludedFields)
ну и естественно для разных классов одинаковые имена отдельно друг от друга настраиваются

2020-11-25 08:52 UTC, NataashaBanan commented on ObjectPrinting/PrintingConfig.cs
> +            return obj is IEnumerable collection ? PrintToStringIenumerable(collection) : PrintToString(obj, 0);
Поменяла

2020-11-25 08:52 UTC, NataashaBanan commented on ObjectPrinting/PrintingConfig.cs
> +        public readonly Dictionary<Type, CultureInfo> Cultures = new Dictionary<Type, CultureInfo>();
Переделала

2020-11-25 08:53 UTC, NataashaBanan commented on ObjectPrinting/PrintingConfig.cs
> +        public readonly Dictionary<Delegate, int> TrimForStringProperties = new Dictionary<Delegate, int>();
Изменила

2020-11-25 08:53 UTC, NataashaBanan commented on ObjectPrinting/PrintingConfig.cs
> +                switch (obj)
Поменяла

2020-11-25 10:54 UTC, NataashaBanan commented on ObjectPrinting/PrintingConfig.cs
> +            if (SerializationsForType.TryGetValue(obj.GetType(), out var func))
Нужно выбрать что-то одно или как?

2020-11-25 10:55 UTC, NataashaBanan commented on ObjectPrinting/PrintingConfig.cs
> +            foreach (var func in excludedFields)
Как можно вытащить имя из memberSelector?

2020-11-25 10:59 UTC, NataashaBanan commented on ObjectPrinting/PropertyPrintingConfig.cs
> +        public readonly Func<TOwner, TPropType> MemberSelector;
Я обращаюсь к этому полю из Extensions, а как к нему обращаться, если не будет публичным?

2020-11-25 11:01 UTC, NataashaBanan commented on ObjectPrinting/PropertyPrintingConfig.cs
> +        public PrintingConfig<TOwner> Using(CultureInfo culture)
Для этого тоже сделать класс расширение и в нём для каждого числового типа прописать метод?

2020-11-26 10:28 UTC, goodoldlameme commented on ObjectPrinting/PrintingConfig.cs
> +            if (SerializationsForType.TryGetValue(obj.GetType(), out var func))
Надо чтобы если настройка для типа и для поля по имени есть, они обе сработали на поле такого типа и с таким именем

2020-11-26 10:38 UTC, goodoldlameme commented on ObjectPrinting/PrintingConfig.cs
> +            foreach (var func in excludedFields)
google => expression get property name

2020-11-26 10:44 UTC, goodoldlameme commented on ObjectPrinting/PropertyPrintingConfig.cs
> +        public PrintingConfig<TOwner> Using(CultureInfo culture)
ага, правильно поняла, обрати внимание, что для DateTime культуру единообразно со всеми остальными типами нельзя будет применить

2020-11-26 10:45 UTC, goodoldlameme commented on ObjectPrinting/PropertyPrintingConfig.cs
> +        public readonly Func<TOwner, TPropType> MemberSelector;
каст к интерфейсу

2020-11-26 11:04 UTC, goodoldlameme requested changes

2020-11-26 11:04 UTC, goodoldlameme commented on ObjectPrinting/PropertyPrintingConfigExtension.cs
> +            var printingConfig = ((IPropertyPrintingConfig<TOwner, string>) propConfig).ParentConfig;
ты вот спрашивала как тебе Name получить, если он будет приватным в классе - он должен быть полем интерфейса и, сделав к нему каст, получишь его

2020-11-26 11:04 UTC, goodoldlameme commented on ObjectPrinting/PropertyPrintingConfigExtension.cs
> +                    propConfig.MemberName, str => str.Substring(0, maxLen));
сейчас будет ошибка, если maxLen больше длины строки, которую обрезаешь

2020-11-26 14:10 UTC, NataashaBanan commented on ObjectPrinting/PropertyPrintingConfigExtension.cs
> +            var printingConfig = ((IPropertyPrintingConfig<TOwner, string>) propConfig).ParentConfig;
Сделала

2020-11-26 14:11 UTC, NataashaBanan commented on ObjectPrinting/PropertyPrintingConfig.cs
> +                Console.WriteLine(MemberName);
Убрала

2020-11-26 14:39 UTC, NataashaBanan commented on ObjectPrinting/PrintingConfig.cs
> +            if (SerializationsForType.TryGetValue(obj.GetType(), out var func))
Поправила, дописала тест

2020-11-26 14:40 UTC, NataashaBanan commented on ObjectPrinting/PrintingConfig.cs
> +            foreach (var func in excludedFields)
ой ой, пыталась достать из скомпиленного expression. Поправила.

2020-11-26 14:40 UTC, NataashaBanan commented on ObjectPrinting/PropertyPrintingConfig.cs
> +        public readonly Func<TOwner, TPropType> MemberSelector;
Сделала

2020-11-26 14:46 UTC, NataashaBanan commented on ObjectPrinting/PrintingConfig.cs
> +            if (SerializationForProperty.ContainsKey(propertyInfo.Name))
А теперь там два метода таких, и будет не слишком хорошо выглядеть. Или всё равно сделать?

2020-11-26 14:55 UTC, NataashaBanan commented on ObjectPrinting/PropertyPrintingConfigExtension.cs
> +                    propConfig.MemberName, str => str.Substring(0, maxLen));
Поправила

2020-11-26 15:33 UTC, NataashaBanan commented on ObjectPrinting/PropertyPrintingConfig.cs
> +        public PrintingConfig<TOwner> Using(CultureInfo culture)
Написала тест, вроде, работает. Или что-то не то?

2020-11-26 15:37 UTC, NataashaBanan commented on ObjectPrinting/PrintingConfig.cs
> +        private readonly Dictionary<string, Delegate> SerializationForProperty = new Dictionary<string, Delegate>();
Не совсем поняла, что имеется в виду.

2020-11-26 18:27 UTC, NataashaBanan commented on ObjectPrinting/PrintingConfig.cs
>              foreach (var propertyInfo in type.GetProperties())
Сделала

2020-11-27 12:56 UTC, goodoldlameme commented on ObjectPrinting/PrintingConfig.cs
> +            if (SerializationForProperty.ContainsKey(propertyInfo.Name))
так и без этого все равно 2 метода получается, просто так все в кучу получается скинуто

2020-11-27 12:57 UTC, goodoldlameme commented on ObjectPrinting/PrintingConfig.cs
> +            if (SerializationForProperty.ContainsKey(propertyInfo.Name))
плюс TryGet в имени подразумевает, что что-то вернуться должно(не bool, а, например, через out параметр), но этот метод просто модифицирует переданный sb, так что тут еще нужно с неймингом как-то поработать в любом случае

2020-11-27 12:58 UTC, goodoldlameme commented on ObjectPrinting/PrintingConfig.cs
> +        private readonly Dictionary<string, Delegate> SerializationForProperty = new Dictionary<string, Delegate>();
такой пример `class Foo
{
    public string Name { get; set; }
}

class Bar
{
    public Foo Foo { get; set; }
    public string Name { get; set; }
}

[Test]
public void FooBar()
{
    var foo = new Bar {Foo = new Foo {Name = "Hello"}, Name = "World"};
    var printer = ObjectPrinter.For<Bar>().Excluding(b => b.Name);
    var actual = printer.PrintToString(foo);
    actual.Should().Contain("Name = Hello");
}
`

2020-11-27 13:19 UTC, goodoldlameme requested changes

2020-11-27 13:19 UTC, goodoldlameme commented on ObjectPrinting/PropertyPrintingConfigExtension2.cs
> +    public static class PropertyPrintingConfigExtension2
не обязательно было еще один класс с расширениями делать, можно было просто в том же писать

2020-11-27 13:19 UTC, goodoldlameme commented on ObjectPrinting/Tests/PrintingConfigTests.cs
> +                .Contain("11/11/2020");
работать работает, но тест не очень удачный, так как в некоторых культурах день и месяц местами меняются

2020-11-27 13:19 UTC, goodoldlameme commented on ObjectPrinting/PrintingConfig.cs
> +        private string GetNumberWithCultureOrNull(object obj)
стоит переименовать, раз теперь не только у цифр культуры меняем

2020-11-27 16:01 UTC, NataashaBanan commented on ObjectPrinting/PropertyPrintingConfigExtension2.cs
> +    public static class PropertyPrintingConfigExtension2
Перенесла.

2020-11-27 16:07 UTC, NataashaBanan commented on ObjectPrinting/PrintingConfig.cs
> +        private string GetNumberWithCultureOrNull(object obj)
Переименовала

2020-11-27 16:11 UTC, NataashaBanan commented on ObjectPrinting/Tests/PrintingConfigTests.cs
> +                .Contain("11/11/2020");
И правда, не подумала, изменила.

2020-11-27 16:51 UTC, NataashaBanan commented on ObjectPrinting/PrintingConfig.cs
> +        private readonly Dictionary<string, Delegate> SerializationForProperty = new Dictionary<string, Delegate>();
Поправила, добавила тест.

2020-11-27 16:54 UTC, NataashaBanan commented on ObjectPrinting/PrintingConfig.cs
> +            if (SerializationForProperty.ContainsKey(propertyInfo.Name))
удалила доп методы, прописала всё внутри PrintMember

2020-11-29 09:00 UTC, goodoldlameme requested changes

2020-11-29 09:00 UTC, goodoldlameme commented on ObjectPrinting/PrintingConfig.cs
> +        private List<object> serializedObjects = new List<object>();
поле можно сделать readonly

2020-11-29 13:39 UTC, NataashaBanan commented on ObjectPrinting/PrintingConfig.cs
> +            if (excludedTypes.Contains(type) || (parent is TOwner && excludedFields.Contains(name)))
Поправила с помощью declaringType и для исключения и для сериализации. Дописала тесты

2020-11-29 14:06 UTC, NataashaBanan commented on ObjectPrinting/PrintingConfig.cs
> +        private List<object> serializedObjects = new List<object>();
ой а его больше нет

2020-11-29 14:16 UTC, NataashaBanan commented on ObjectPrinting/PrintingConfig.cs
> +            foreach (var serilizedObj in serializedObjects)
Теперь храню что-то вроде стека сериализации. Дописала тест на такой случай.

2020-11-30 07:32 UTC, goodoldlameme requested changes

2020-11-30 07:32 UTC, goodoldlameme commented on ObjectPrinting/PrintingConfig.cs
> +            {
скобки можно убрать

2020-11-30 07:32 UTC, goodoldlameme commented on ObjectPrinting/PrintingConfig.cs
> +        private string PrintToString(object obj, int nestingLevel, List<object> serializedObjects)
тут SerializedObjects тоже можно бы сделать HashSet

2020-11-30 07:32 UTC, goodoldlameme commented on ObjectPrinting/PrintingConfig.cs
> +        private void PrintMember(string name, object value, Type type, object parent, StringBuilder sb,
тут можно уменьшить количество параметров, если использовать общий для PropertyInfo и FieldInfo класс MemberInfo и написать метод расширения GetValue для него, получится 
```
private void PrintMember(MemberInfo memberInfo, object parent, StringBuilder sb,
            int nestingLevel, HashSet<object> serilizedObjects)
```

2020-11-30 10:39 UTC, NataashaBanan commented on ObjectPrinting/PrintingConfig.cs
> +            {
Убрала

2020-11-30 10:46 UTC, NataashaBanan commented on ObjectPrinting/PrintingConfig.cs
> +        private string PrintToString(object obj, int nestingLevel, List<object> serializedObjects)
Cделала

2020-11-30 11:16 UTC, NataashaBanan commented on ObjectPrinting/PrintingConfig.cs
> +        private void PrintMember(string name, object value, Type type, object parent, StringBuilder sb,
Поправила

2020-11-30 12:19 UTC, goodoldlameme approved these changes

2022-11-01 05:47 UTC, closed without merging